// Beach data for Nexplore
export const BEACHES = [
  {
    id: 'beach-001',
    title: 'Baker Beach',
    city: 'San Francisco',
    category: 'Beach',
    eventType: 'beach',
    free: true,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop',
    description: 'Wide sandy beach with dramatic Golden Gate Bridge views and picnic areas.',
    tags: [
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://presidio.gov/explore/attractions/baker-beach-2',
    fullAddress: '1770 Gibson Rd, San Francisco, CA 94129',
    isEditorPick: false,
  },
  {
    id: 'beach-002',
    title: 'Natural Bridges State Beach',
    city: 'Santa Cruz',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=500&h=400&fit=crop',
    description: 'Outstanding Marine Protected Area with abundant tidepool life. Best at 2ft or lower low tide.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/naturalbridges',
    fullAddress: 'Swift St. south from Hwy 1, Santa Cruz, CA 95060',
    isEditorPick: true,
  },
  {
    id: 'beach-003',
    title: 'SeaCliff State Beach',
    city: 'Aptos',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=400&fit=crop',
    description: 'Family-friendly sandy beach with a fishing pier, campground and accessible facilities.',
    tags: [
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/?page_id=543',
    fullAddress: 'Aptos, CA 95003',
    isEditorPick: false,
  },
  {
    id: 'beach-004',
    title: 'Half Moon Bay State Beach',
    city: 'Half Moon Bay',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop',
    description: 'Four connected sandy beaches with a free all-terrain beach wheelchair and coastal trail.',
    tags: [
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/halfmoonbay',
    fullAddress: '95 Kelly Avenue, Half Moon Bay, CA 94019',
    isEditorPick: false,
  },
  {
    id: 'beach-005',
    title: 'Asilomar State Beach',
    city: 'Pacific Grove',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=400&fit=crop',
    description: 'Rocky shore paradise with excellent tidepool areas monitored by LiMPETS scientists.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
    ],
    officialUrl: 'https://www.parks.ca.gov/asilomar',
    fullAddress: 'Pacific Grove, CA 93950',
    isEditorPick: true,
  },
  {
    id: 'beach-006',
    title: 'Fitzgerald Marine Reserve',
    city: 'Moss Beach',
    category: 'Beach',
    eventType: 'beach',
    free: true,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1511593358241-7eea1f3c84e5?w=500&h=400&fit=crop',
    description: 'Outstanding FREE tidepool reserve. Explore 1 hour before and after low tide.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
    ],
    officialUrl: 'https://fitzgeraldreserve.org',
    fullAddress: '200 Nevada Ave, Moss Beach, CA 94038',
    isEditorPick: true,
  },
  {
    id: 'beach-007',
    title: 'San Gregorio State Beach',
    city: 'San Gregorio',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1495995424223-4d71bcdd2085?w=500&h=400&fit=crop',
    description: 'Scenic beach 10.5 miles south of Half Moon Bay with tidepool areas.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/?page_id=529',
    fullAddress: 'La Honda Rd & Cabrillo Hwy, San Gregorio, CA',
    isEditorPick: false,
  },
  {
    id: 'beach-008',
    title: 'Bean Hollow State Beach',
    city: 'Pescadero',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=400&fit=crop',
    description: 'Rocky beach with excellent tidepool areas and picnic facilities.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/?page_id=527',
    fullAddress: '11000 Cabrillo Hwy, Pescadero, CA',
    isEditorPick: false,
  },
  {
    id: 'beach-009',
    title: 'Pescadero State Beach',
    city: 'Pescadero',
    category: 'Beach',
    eventType: 'beach',
    free: false,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=400&fit=crop',
    description: 'Multiple parking areas with tidepool access and scenic views.',
    tags: [
      { tag_group: 'amenity', name: 'tidepool' },
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parks.ca.gov/?page_id=522',
    fullAddress: 'CA-1, Pescadero, CA',
    isEditorPick: false,
  },
  {
    id: 'beach-010',
    title: 'Fort Funston',
    city: 'San Francisco',
    category: 'Beach',
    eventType: 'beach',
    free: true,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=400&fit=crop',
    description: 'Wild dune-backed beach below the bluffs, known for hang gliders and off-leash dogs.',
    tags: [
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
      { tag_group: 'amenity', name: 'wheelchair-accessible' },
    ],
    officialUrl: 'https://www.parksconservancy.org',
    fullAddress: '206 Fort Funston Rd, San Francisco, CA',
    isEditorPick: false,
  },
  {
    id: 'beach-011',
    title: 'Poplar Beach',
    city: 'Half Moon Bay',
    category: 'Beach',
    eventType: 'beach',
    free: true,
    startDate: null,
    endDate: null,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop',
    description: 'Easy-access sandy beach with bluff-top trail parking, popular for horseback riding.',
    tags: [
      { tag_group: 'amenity', name: 'parking-onsite' },
      { tag_group: 'amenity', name: 'restrooms' },
    ],
    officialUrl: 'https://www.visithalfmoonbay.org/places/poplar-beach/',
    fullAddress: 'Half Moon Bay, CA',
    isEditorPick: false,
  },
]
